[package]
name = "coordenadas"
version = "0.1.2"
authors = ["marcio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.7.0"
regex = "1.1.7"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
