[package]
name = "coordenadas"
version = "1.0.0"
authors = ["marcio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.2.0", package = "gtk4" }
regex = "1.5.4"
csv = "1.1.6"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
